[package]
name = "bookends"
version = "0.1.0"
authors = ["Robb Shecter <robb@public.law>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo = "0.46.0"
clap  = "2.33.1"